apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-f0bn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-f0bn
    app.kubernetes.io/part-of: ci1t-830-0018-app
  name: devfile-sample-f0bn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-f0bn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-f0bn
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0018-tenant/ci1t-830-0018-app/devfile-sample-f0bn@sha256:c536b3559d2d53d68b8475a19de3c1763655996f128047c6d93980ed13f4545c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
